apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kabanero-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: kabanero/kabanero-operator-registry:0.3.0-alpha.1
  publisher: kabanero.io
  displayName: Kabanero Operators
