apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  # Add anywhere else you want serverless goodies to work
  - knative-serving
  - openshift-pipelines
  - kabanero