apiVersion: v1
kind: Namespace
metadata:
 name: kabanero
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kabanero
  namespace: kabanero
spec:
  targetNamespaces:
  - kabanero
