apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-dev-preview-community-operators-openshift-marketplace
  namespace: openshift-operators
spec:
  channel: dev-preview
  config:
    resources: {}
  installPlanApproval: Manual
  name: openshift-pipelines-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator.v0.7.0
