apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: knative-eventing-operator-alpha-community-operators-openshift-marketplace
  namespace: openshift-operators
spec:
  channel: alpha
  config:
    resources: {}
  installPlanApproval: Manual
  name: knative-eventing-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: knative-eventing-operator.v0.8.0