apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eclipse-che
  namespace: kabanero
spec:
  channel: stable
  installPlanApproval: Manual
  name: eclipse-che
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: eclipse-che.v7.3.0
