apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-operators
spec:
  channel: techpreview
  installPlanApproval: Manual
  name: serverless-operator
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: serverless-operator.v1.1.0